### ISSUE TITLE
Image type

### ISSUE THREAD

**Issue by aulisius** [prajwalkr/SnapSudoku#1]
What type of images can this process ? JPEG, PNG, BMP ?

I am thinking of making a web service with this, so would be helpful to know what type of data to transfer :)

**Comment by prajwalkr** [comment]
```
    Windows bitmaps - *.bmp, *.dib (always supported)
    JPEG files - *.jpeg, *.jpg, *.jpe (see the Notes section)
    JPEG 2000 files - *.jp2 (see the Notes section)
    Portable Network Graphics - *.png (see the Notes section)
    Portable image format - *.pbm, *.pgm, *.ppm (always supported)
    Sun rasters - *.sr, *.ras (always supported)
    TIFF files - *.tiff, *.tif (see the Notes section)
```

Taken from: http://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html?highlight=imread#imread

Although there are quite a few significant improvements yet to be done to the existing code of SnapSudoku, I'll be only more than happy if you could make it a web service. We could work together in building it! 
You can always drop me a mail: prajwalrenukanand@gmail.com :smile:

**Comment by aulisius** [comment]
:+1:
