### ISSUE TITLE
Add code to solve the Sudoku puzzle

### ISSUE THREAD

**Issue by cclauss** [prajwalkr/SnapSudoku#2]
[Peter Norvig](http://norvig.com) of Google has a [really interesting Sudoku solver](http://norvig.com/sudoku.html) in Python that is a wonderful read.  The average time to solve a random Sudoku puzzle is 0.01 seconds.

**Comment by prajwalkr** [comment]
Fixed all bugs, thanks to you, SnapSudoku is fully functional :blush:
