### ISSUE TITLE
Run SnapSudoku on a smart phone

### ISSUE THREAD

**Issue by cclauss** [prajwalkr/SnapSudoku#3]
It would be cool to get [SnapSudoku running on the iPhone](https://forum.omz-software.com/topic/3050/snapsudoku) so that you could use the camera to do the snap and immediately solve the puzzle right on the phone.  _It would drive Sudoku players crazy if you could walk up with your smart phone, snap a picture of their puzzle, and show them the solution._  [Pythonista](http://omz-software.com/pythonista) is a Python 2.7 IDE for iOS and it currently has Python 3.5 support in beta testing.  Pythonista does support NumPy and Pillow (PIL) but does **not** yet support OpenCV or SciPy.

**Comment by aulisius** [comment]
Hey, this is something I was planning too :D 

I was thinking along the lines of a web service with a REST API to which we can POST the image and get the solution in the response. This must be easier than having to create an iOS/Android in non-native language.

**Comment by krishnarb3** [comment]
This already exists on the play store using OpenCV with java / c++ 
Some of these are on github too , so you could check them out.

**Comment by aulisius** [comment]
[Everything that you imagine exists](https://www.reddit.com/r/Psychonaut/comments/322a7c/everything_you_could_ever_possibly_imagine/). Doesn't mean we shouldn't be doing it :)

Plus providing a web API means it can be extended by others rather being locked down in one app

**Comment by cclauss** [comment]
http://sudokugrab.blogspot.com/2009/07/how-does-it-all-work.html
has a good summary of puzzle detection algorithms, and some references on number recognition.
